### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by trishagee** [Azure/azure-docs-sdk-java#1401]
Hi! This page is quite helpful (although I'm not sure if it's up to date or not, a date of 2019 _seems_ recent but Java moves fast these days! I got here via Google so I'm not sure if it's part of the normal help). My main feedback is that there's a broken link on the navigation. The link to IntelliJ on the page is:

    https://docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij?view=azure-java-stable

which takes me to

    https://docs.microsoft.com/en-us/azure/developer/java/tookit-for-intellij

but should (I think?) take me to

    https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a352957d-7f26-dfe0-adaa-3541bb4ec6f6
* Version Independent ID: 72395d7b-69aa-2b61-cc43-cf99d35d484e
* Content: [Java JDKs and long-term support for Azure development](https://docs.microsoft.com/en-us/java/azure/jdk/?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/jdk/index.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/jdk/index.md)
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@KarlErickson - Karl would you please take a look at this issue. Thanks.

**Comment by KarlErickson** [comment]
@trishagee - thanks for the feedback! I'll get that fixed right away. @bmitchell287 thanks for the heads-up.

**Comment by KarlErickson** [comment]
@trishagee there's a problem with the redirection, which I will correct. Please see the current version of the topic at <https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-long-term-support>. Thanks again!
