### ISSUE TITLE
Spring package clean up in docs repo

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-docs-sdk-java#1573]
Several issues around spring packages.

1. Spring boot starter readme update on reference-unified.yml. @yiliuTo 
1. Some of the APIs classify into `Other` [page](https://review.docs.microsoft.com/en-us/java/api/org.slf4j.helpers?view=azure-java-preview&branch=smoke-test). It has to be fixed. @yiliuTo 
1. Three Spring packages (e.g azure-spring-cloud-stream-binder-servicebus-topic) have duplicate uid issue. Tracking in issue: https://ceapex.visualstudio.com/Engineering/_workitems/edit/343892 @anmeng10101

**Comment by yiliuTo** [comment]
Hi @sima-zhu , can I close this issue since currently Spring readme and packages have been removed from the docs repo?
