### ISSUE TITLE
Missing documentation for Azure B2C

### ISSUE THREAD

**Issue by ccit-spence** [Azure/azure-docs-sdk-java#400]
A document explaining how to integrate with the B2C version with a regular Spring MVC application.  No JavaScript frameworks.  Just Spring MVC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cf5423d-6c4c-26a8-89bb-7686794716d0
* Version Independent ID: 734cd358-3dfb-14cd-ee3d-5ce54be8d613
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/Azure/azure-docs-sdk-java/blob/live/docs-ref-conceptual/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by rmcmurray** [comment]
@ccit-spence - we've made changes the the Spring starter which remove the JavaScript dependency, and we've updated the article accordingly:

https://docs.microsoft.com/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory
