### ISSUE TITLE
Message: the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1)

### ISSUE THREAD

**Issue by awsazuser** [Azure/azure-docs-sdk-java#414]
I am getting the following error when I execute Maven command to apply the resource list file to kubernetes cluster(FYI,i am using AKS not ACS)

$ mvn fabric8:apply
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building demo-eureka-service 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- fabric8-maven-plugin:3.5.30:apply (default-cli) @ demo-eureka-service ---
[INFO] F8: Using Kubernetes at https://aksxkcwghf5rmuqw-148bd6e3.hcp.eastus.azmk8s.io:443/ in namespace default with manifest /home/azureuser/AKSspringcloudCICDwtMavenPlugin/demo-eureka-service/target/classes/META-INF/fabric8/kubernetes.yml
[INFO] Using namespace: default
[INFO] Using namespace: default
[INFO] Secret has not changed so not doing anything
[INFO] Updating a Service from kubernetes.yml
[INFO] Updated Service: target/fabric8/applyJson/default/service-eurekaservice-7.json
[INFO] Using namespace: default
[INFO] Creating a Deployment from kubernetes.yml namespace default name eurekaservice
[ERROR] Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://aksxkcwghf5rmuqw-148bd6e3.hcp.eastus.azmk8s.io/apis/extensions/v1beta1/namespaces/default/deployments. Message: the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).. Deployment(apiVersion=apps/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/git-commit=dda6a7a0e722997c479103e55ab00dd266395e01, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=demo-eureka-service&var-version=0.0.1-SNAPSHOT, fabric8.io/scm-tag=HEAD, fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-eureka-service}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=demo-eureka-service, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, name=eurekaservice, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=1, revisionHistoryLimit=2, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={app=demo-eureka-service, provider=fabric8, group=com.example}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=dda6a7a0e722997c479103e55ab00dd266395e01, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=demo-eureka-service&var-version=0.0.1-SNAPSHOT, fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-eureka-service, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master, fabric8.io/scm-tag=HEAD}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=eurekaservice, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=aksdocreg.azurecr.io/demo-eureka-service, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8761, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=180, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), name=eurekaservice, ports=[ContainerPort(containerPort=8761, hostIP=null, hostPort=null, name=null, protocol=null, additionalProperties={}), ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8761, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=10, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), resources=null, securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://aksxkcwghf5rmuqw-148bd6e3.hcp.eastus.azmk8s.io/apis/extensions/v1beta1/namespaces/default/deployments. Message: the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
        at io.fabric8.kubernetes.api.Controller.doCreateResource(Controller.java:1082)
        at io.fabric8.kubernetes.api.Controller.applyResource(Controller.java:1071)
        at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:282)
        at io.fabric8.kubernetes.api.Controller.apply(Controller.java:227)
        at io.fabric8.maven.plugin.mojo.build.ApplyMojo.applyEntities(ApplyMojo.java:414)
        at io.fabric8.maven.plugin.mojo.build.ApplyMojo.executeInternal(ApplyMojo.java:390)
        at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.085 s
[INFO] Finished at: 2018-04-04T15:42:14+00:00
[INFO] Final Memory: 46M/422M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.30:apply (default-cli) on project demo-eureka-service: Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://aksxkcwghf5rmuqw-148bd6e3.hcp.eastus.azmk8s.io/apis/extensions/v1beta1/namespaces/default/deployments. Message: the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1). Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=the API version in the data (apps/v1beta1) does not match the expected API version (extensions/v1beta1), metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).. Deployment(apiVersion=apps/v1beta1, kind=Deployment, metadata=ObjectMeta(annotations={fabric8.io/git-commit=dda6a7a0e722997c479103e55ab00dd266395e01, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=demo-eureka-service&var-version=0.0.1-SNAPSHOT, fabric8.io/scm-tag=HEAD, fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-eureka-service}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=demo-eureka-service, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, name=eurekaservice, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=1, revisionHistoryLimit=2, rollbackTo=null, selector=LabelSelector(matchExpressions=[], matchLabels={app=demo-eureka-service, provider=fabric8, group=com.example}, additionalProperties={}), strategy=null, template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/git-commit=dda6a7a0e722997c479103e55ab00dd266395e01, fabric8.io/metrics-path=dashboard/file/kubernetes-pods.json/?var-project=demo-eureka-service&var-version=0.0.1-SNAPSHOT, fabric8.io/scm-url=https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/demo-eureka-service, fabric8.io/iconUrl=img/icons/spring-boot.svg, fabric8.io/git-branch=master, fabric8.io/scm-tag=HEAD}, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=eurekaservice, provider=fabric8, version=0.0.1-SNAPSHOT, group=com.example}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={})], image=aksdocreg.azurecr.io/demo-eureka-service, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8761, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=180, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), name=eurekaservice, ports=[ContainerPort(containerPort=8761, hostIP=null, hostPort=null, name=null, protocol=null, additionalProperties={}), ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8761, Kind=null, StrVal=null, additionalProperties={}), scheme=HTTP, additionalProperties={}), initialDelaySeconds=10, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), resources=null, securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by brunoborges** [comment]
Can you provide more details on what you are trying to do? Which article/tutorial are you following?

**Comment by joshfree** [comment]
Closing old issue from 2018 with open/unanswered question to original poster.
