### ISSUE TITLE
Problem getting password to "Push your app to the container registry"

### ISSUE THREAD

**Issue by gary555594** [Azure/azure-docs-sdk-java#447]
Statement az acr credential show --name wingtiptoysregistry --query passwords[0] didn't return anything until I added the name of the resource I configured earlier ie
az acr credential show --name wingtiptoysregistry --query passwords[0] --resource-group myresourcegroup

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1bc58a-332c-ccc9-edff-47b175858a85
* Version Independent ID: 57c881ee-265d-0c63-e39e-afb40a241bd3
* Content: [Deploy a Spring Boot App on Kubernetes in Azure Container Service](https://docs.microsoft.com/en-gb/java/azure/spring-framework/deploy-spring-boot-java-app-on-kubernetes?toc=%2Ffr-fr%2Fjava%2Fapi%2F_splitted%2Fcom.microsoft.azure.management%2Ftoc.json&bc=%2Ffr-fr%2Fjava%2Fbreadcrumb%2Ftoc.json)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @rmcmurray
* Microsoft Alias: **asirveda;robmcm**

**Comment by andxu** [comment]
@gary555594 would you please try it again, the resource group argument is not required for querying password, so the following command is valid:
```
az acr credential show --name wingtiptoysregistry --query passwords[0]
```
