### ISSUE TITLE
Link to Event Hub Client API is outdated

### ISSUE THREAD

**Issue by doneuros** [Azure/azure-docs-sdk-java#456]
[Enter feedback here]
"Explore the Client API" link is outdated:
https://docs.microsoft.com/en-us/java/api/overview/azure/eventhub/client
And for the dependency I think there is a version 1.0.1 which changes Interfaces and can't be used as descripted. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9ec650-aaa6-c588-8956-085e85c81260
* Version Independent ID: 6590e484-b5fc-1135-3280-ebae04ceab3a
* Content: [Azure Event Hub libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/eventhub)
* Content Source: [docs-ref-services/eventhub.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/eventhub.md)
* Service: **event-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by joshfree** [comment]
Closing old issue from 2018.  The docs site has since been revised.

https://docs.microsoft.com/en-us/azure/developer/java/sdk/
