### ISSUE TITLE
Error: A redirect is required to get the users approval

### ISSUE THREAD

**Issue by maheshreddy77** [Azure/azure-docs-sdk-java#499]
The sample application is not working, Getting below error

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Mon Jun 04 07:47:28 IST 2018
There was an unexpected error (type=Internal Server Error, status=500).
A redirect is required to get the users approval

https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

**Comment by rmcmurray** [comment]
Thanks, @maheshreddy77 - this is related to the problem that we're tracking in issue #410; we're currently looking into that. Hopefully we will have something soon, but for now - as I mentioned in the other issue, you can use the example [azure-active-directory-spring-boot-sample](https://github.com/Microsoft/azure-spring-boot/tree/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample) application as a starting point for building an application; that sample has been tested and it works as expected.

**Comment by rmcmurray** [comment]
Hello @maheshreddy77  - we published a new version of that article several weeks ago that addresses the problems that we identified. Please see the following updated article for more:

https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory

Thanks!
