### ISSUE TITLE
Broken links under "Samples"

### ISSUE THREAD

**Issue by ullgren** [Azure/azure-docs-sdk-java#509]
Under "Samples" following the "Manage groups, users, and roles" link gives a 404 response. 
Following the "Call the Active AD Graph API from your Java web app" link goes to an archived repo. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7c08c2-46b8-a626-7fbd-7b8572bcd84c
* Version Independent ID: e484d54c-8c14-db0a-1516-69cf0710061c
* Content: [Azure Active Directory libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/activedirectory)
* Content Source: [docs-ref-services/activedirectory.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/activedirectory.md)
* Service: **active-directory**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rncwnd79** [comment]
"Explore the Management APIs" button is also 404.

This page seems to be a collection of dead links :(
