### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by rangv** [Azure/azure-docs-sdk-java#533]
Explore Client APIs link is broken - gives 404 - Page not found error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c1df2f1-d67a-3f74-6940-57afa8435aad
* Version Independent ID: fd1db557-7066-9df2-3beb-1566d74d360e
* Content: [Azure IoT Hub libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/iot?view=azure-java-stable)
* Content Source: [docs-ref-services/iot.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/iot.md)
* Service: **iot-hub**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by singhraminder** [comment]
This link is working fine and redirecting to h[ttps://docs.microsoft.com/en-us/java/api/overview/azure/iot/client?view=azure-java-stable](https://docs.microsoft.com/en-us/java/api/overview/azure/iot/client?view=azure-java-stable)
Please confirm.

**Comment by robinsh** [comment]
@reassign:robinsh from rangv to me.

**Comment by robinsh** [comment]
#reassign:robinsh

**Comment by robinsh** [comment]
#reassign:robinsh

**Comment by robinsh** [comment]
The big "Explore the Client APIs" button does work. It directs to: https://docs.microsoft.com/en-us/java/api/overview/azure/iot/client?view=azure-java-stable. So I think this issue can be closed. 
#please-close 
/cc: @singhraminder

**Comment by robinsh** [comment]
This GH issue has two links in it: 
•	Content: Azure IoT Hub libraries for Java
•	Content Source: docs-ref-services/iot.md

If you go to the link for ‘Content” and look at the blue button labelled “Explore Client APIs”, it points to here: Azure IoT Hub libraries for Java 
If you click on that link, it shows a rendered article. If you go down to the blue “Explore the Client APIs” button in that article and click it, it works fine. It goes to here: https://docs.microsoft.com/en-us/java/api/overview/azure/iot/client?view=azure-java-stable 

However, for “Content Source”, this is a link to docs-ref-services/iot.md. If you click on that link, it shows a different rendered article. If you go down to where it says [!div class=”nextstepaction”] “Explore the Client APIs”, it links to https://github.com/Azure/azure-docs-sdk-java/blob/master/java/api/overview/azure/iot/client  If you click that link, you get a 401 error. 
One of those links needs to be fixed. 

Can you change the hyperlink for docs-refs-services/iot.md to point to the same place as the Content? I’m not 100% clear on how to fix this, but we definitely have an error. Is this an error in the SDK? 

/cc: @singhraminder

**Comment by robinsh** [comment]
#reassign:robinsh

**Comment by robinsh** [comment]
It looks like the second link now works, so both the Content and the Content Source have working links. That being the case, I think this issue can be closed. #please-close

**Comment by robinsh** [comment]
#please-close

**Comment by robinsh** [comment]
#please-close
/cc: @philmea
