### ISSUE TITLE
Links to explore APIs not working

### ISSUE THREAD

**Issue by alejandrosanchezcabana** [Azure/azure-docs-sdk-java#535]
Links for exploration are not working, lateral menu is fine, but buttons doesn't work.

working: https://docs.microsoft.com/en-us/java/api/keyvault/management?view=azure-java-stable
not working: https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault/management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52924023-b9de-6100-0078-44a935e6e8c4
* Version Independent ID: 40879875-3240-017a-75e6-d18996a6295a
* Content: [Azure Key Vault libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault?view=azure-java-stable)
* Content Source: [docs-ref-services/keyvault.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/keyvault.md)
* Service: **keyvault**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by prashanthyv** [comment]
Hi @alejandrosanchezcabana, 

Thanks for reporting this. 
Where did you find and why are you trying to use this link - https://docs.microsoft.com/en-us/java/api/overview/azure/keyvault/management?

**Comment by alejandrosanchezcabana** [comment]
Hi @prashanthyv 
If you go to https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/keyvault.md
and click on 'Explore the Client APIs' you will see the broken link. :)

**Comment by joshfree** [comment]
Closing old issue from 2018; verified link has since been corrected.
