### ISSUE TITLE
Question about Azure spring boot starter for AD usage

### ISSUE THREAD

**Issue by capadon1131** [Azure/azure-docs-sdk-java#549]
Hi,

I just finished running through the example here: https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory, and I have a couple of questions.

First, my expectation was that upon initial navigation to http://localhost:8080 the redirect would be to the Microsoft login page (i.e. https://login.microsoftonline.com...). However, instead the redirect was to http://localhost:8080/login, and the user must click an "Azure" link to navigate to the Microsoft login page.

It looks like this is the default behavior provided by the HttpSecurity.oauth2Login() operation. Do you have any guidance on how to configure this so that it defaults to azure as the provider - eliminating the need for the default, generated login page?

Second, the example in the article appears to be specific to Spring Boot 2.0.x. Are there any examples for Spring Boot 1.5.x available?

Thanks

**Comment by joshfree** [comment]
Closing old issue from 2018.  If there's additional questions on azure-spring please feel free to reactivate or open an issue in the https://github.com/azure/azure-sdk-for-java repo where the azure-spring-boot starters live.  Thanks
