### ISSUE TITLE
Click on "Explore the Management APIs" goes to 400 page 

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-docs-sdk-java#554]
[Enter feedback here]
1. Click on the "Explore the Management APIs" goes to 400 pages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7c08c2-46b8-a626-7fbd-7b8572bcd84c
* Version Independent ID: e484d54c-8c14-db0a-1516-69cf0710061c
* Content: [Azure Active Directory libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/activedirectory?view=azure-java-stable)
* Content Source: [docs-ref-services/activedirectory.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/activedirectory.md)
* Service: **active-directory**
* Product: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rloutlaw** [comment]
Fixed in #555
