### ISSUE TITLE
pom dependences

### ISSUE THREAD

**Issue by StankoStan** [Azure/azure-docs-sdk-java#604]
That copy-paste pom.xml will not work, as it will throw the errors:
java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonGenerator.writeStartObject......

the issue is that maven will show the older Jackson-core-2.6.0.jar, as dependency hierarchy says: Jackson-core: 2.9.4 (omitted for conflict with 2.6.0)
Jackson-databind-2.9.4
Jackson-datatype-joda-2.9.4
Jackson-annotations-2.9.0

after forcing 2.9.4 for core, everything went fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef94796e-1bef-becf-b065-3034eb50c0e5
* Version Independent ID: 3fba7a2d-a0b6-6adf-61de-df5c15920284
* Content: [Get started with Azure for Java using Eclipse](https://docs.microsoft.com/en-us/java/azure/eclipse/java-sdk-azure-get-started-eclipse?view=azure-java-preview#feedback)
* Content Source: [preview/docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/preview/docs-ref-conceptual/eclipse/java-sdk-azure-get-started-eclipse.md)
* Service: **multiple**
* Product: **azure**
* GitHub Login: @roygara
* Microsoft Alias: **v-rogara**

**Comment by brunoborges** [comment]
@JonathanGiles this is a classpath dependency conflict issue

**Comment by alzimmermsft** [comment]
The links mentioned in the issue no longer exist and this is the closest equivalent I was able to find: https://docs.microsoft.com/en-us/azure/developer/java/sdk/get-started

This new link getting started guide no longer has the aforementioned issue, so I will close this out.
