### ISSUE TITLE
Broken link on 'Azure Storage libraries for Java' page

### ISSUE THREAD

**Issue by ksurendra** [Azure/azure-docs-sdk-java#627]
On this page https://docs.microsoft.com/en-us/java/api/overview/docs-ref-conceptual/java-sdk-manage-storage-accounts?view=azure-java-stable , the link under 
Samples > Manage Azure Storage accounts is broken (https://docs.microsoft.com/en-us/java/api/overview/docs-ref-conceptual/java-sdk-manage-storage-accounts?view=azure-java-stable) shows a 404 page 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57d1b3c-813e-5c48-4ed7-013f11473f7f
* Version Independent ID: 8b2f0d3f-d959-d5bc-7b47-521248ac056c
* Content: [Azure Storage libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
* Content Source: [docs-ref-services/storage.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* Product: **azure**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by tamram** [comment]
@ksurendra - Thanks for your feedback! This page has been updated. It's now here: 
 https://docs.microsoft.com/en-us/java/api/overview/azure/storage
