### ISSUE TITLE
Install CLI should be before everything

### ISSUE THREAD

**Issue by brunoborges** [Azure/azure-docs-sdk-java#665]
Yah

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot JAR file app to the cloud with Maven and Azure](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm;kevinzha;brborges**

**Comment by rmcmurray** [comment]
Installing the CLI is already the first item in the *Prerequisites* section. Is there something more that you're looking for?

**Comment by brunoborges** [comment]
Keep reading the article. It has a section later on

**Comment by rmcmurray** [comment]
Ah, now I get it. ;-)

I'll fix that ASAP.

**Comment by rmcmurray** [comment]
See https://github.com/Azure/azure-docs-sdk-java/pull/668
