### ISSUE TITLE
Exception: A required class was missing

### ISSUE THREAD

**Issue by ttworek** [Azure/azure-docs-sdk-java#749]
d
d
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------&lt; org.springframework:gs-spring-boot &gt;-----------------
[INFO] Building gs-spring-boot 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- azure-webapp-maven-plugin:1.4.0:deploy (default-cli) @ gs-spring-boot ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.502 s
[INFO] Finished at: 2019-01-05T14:51:08-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project gs-spring-boot: Execution default-cli of goal com.microsoft.azure:azure-webapp-maven-plug
in:1.4.0:deploy failed: A required class was missing while executing com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy: javax/xml/bind/JAXBException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin&gt;com.microsoft.azure:azure-webapp-maven-plugin:1.4.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

Received the above exception while following this tutorial.  Also tried using the latest version (1.5.1), same error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot JAR file app to the cloud with Maven and Azure](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by stefano-detoni** [comment]
I am encountering the same error. I tried also with VisualStudio Code tutorial and has the same issue: JAXBException.
Also please provide more information on how to manually deploy a JAR using ftp: documentation is absent or insufficient: hot to configure environment variables or parameters to the jar execution?
Thanks

**Comment by rmcmurray** [comment]
This has been fixed in #929. The problem was the version of the Maven Plugin, which was updated to 1.6.0.
