### ISSUE TITLE
How to connect to Government cloud using IntelliJ Idea

### ISSUE THREAD

**Issue by Anand-Moghe** [Azure/azure-docs-sdk-java#751]
How to connect to Azure Government Cloud (MAG) using IntelliJ Idea with Azure toolkit for IntelliJ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa34d7c-540d-1d7d-5fd8-6c8effee5e6f
* Version Independent ID: 79d37bb2-eda3-9e7c-bd73-fe9a9055939a
* Content: [Azure Toolkit for IntelliJ](https://docs.microsoft.com/en-us/java/azure/intellij/azure-toolkit-for-intellij?view=azure-java-stable)
* Content Source: [docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/intellij/azure-toolkit-for-intellij.md)
* Service: **multiple**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by mtc3bmtc3b** [comment]
Or more generally: how can we use the Azure Toolkit for IntelliJ to develop and deploy Java applications to an on-prem Azure cloud?  The toolkit seems to assume deployments are to the public Azure cloud.

**Comment by Anand-Moghe** [comment]
To solve the issue for Azure Gov Cloud, create AzureToolsForIntelliJ folder under c:\Users\{userName}.
Then create a file called **AadProvider.json** and add following content:
```
{
"EnvironmentName": "US_GOVERNMENT"
}
```

**Comment by brunoborges** [comment]
@Matthew-Dong fyi
