### ISSUE TITLE
Command needs minor correction

### ISSUE THREAD

**Issue by abhibee** [Azure/azure-docs-sdk-java#803]
There is a missing space in this command (after wingtiptoys-kubernetes):
az acr create --admin-enabled --resource-group wingtiptoys-kubernetes--location eastus \
 --name wingtiptoysregistry --sku Basic

It should be :
az acr create --admin-enabled --resource-group wingtiptoys-kubernetes --location eastus \
 --name wingtiptoysregistry --sku Basic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1bc58a-332c-ccc9-edff-47b175858a85
* Version Independent ID: 57c881ee-265d-0c63-e39e-afb40a241bd3
* Content: [Deploy a Spring Boot App on Kubernetes in Azure Kubernetes Service](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-on-kubernetes?view=azure-java-stable#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-on-kubernetes.md)
* Service: **multiple**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by andxu** [comment]
thanks for the finding, I have already fixed the typo.
