### ISSUE TITLE
Dependency version is old

### ISSUE THREAD

**Issue by yoshioterada** [Azure/azure-docs-sdk-java#806]
[Enter feedback here]
In the documents, old dependency version was wrote as 1.0.8.
However now the version is 2.3.1. So please modify the version?

```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-web</artifactId>
            <version>2.3.1</version>
        </dependency>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fe1c72-eef2-fc3a-975a-bcc1c3c50d19
* Version Independent ID: e4d3b889-4643-2ffa-6632-73ffbb599677
* Content: [Azure Application Insights libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/appinsights?view=azure-java-stable#feedback)
* Content Source: [docs-ref-services/appinsights.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/appinsights.md)
* Service: **appinsights**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brunoborges** [comment]
@yoshioterada can you please submit a PR associated to this issue?

**Comment by yoshioterada** [comment]
Dear 
@brunoborges san

Thank you so much !!
After confirmed the version, it already modified.
So I will close this issue.
