### ISSUE TITLE
Deployment fails with timeout

### ISSUE THREAD

**Issue by altumano** [Azure/azure-docs-sdk-java#808]
[ERROR] Failed to execute goal com.microsoft.azure:azure-webapp-maven-plugin:1.4.0:deploy (default-cli) on project gs-spring-boot: The zip deploy failed after 3 times of retry. -&gt; [Help 1]

Fixed by upgrading azure-webapp-maven-plugin to 1.5.4 in pom.xml

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot JAR file app to the cloud with Maven and Azure](https://docs.microsoft.com/en-gb/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by rmcmurray** [comment]
This has been fixed in #929
