### ISSUE TITLE
The title of this page is wrong 

### ISSUE THREAD

**Issue by yoshioterada** [Azure/azure-docs-sdk-java#840]
Wrong : "Azure Traffic Manager libraries for Java"
Correct:  "Azure DNS libraries for Java"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92c03e84-81f2-25c4-051c-279f7393c2d0
* Version Independent ID: 45c7aa25-b109-8f00-45fd-cf6a0bbc2642
* Content: [Azure DNS libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/dns?view=azure-java-stable)
* Content Source: [docs-ref-services/dns.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/dns.md)
* Service: **dns**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brunoborges** [comment]
@yoshioterada any chance you can submit a PR?

**Comment by yoshioterada** [comment]
Dear @brunoborges san !!
Thank you so much ! I send the Pull Request.

So I will close this issue!
Thank you so much for your advise.

Best Regards.
Yoshio.
