### ISSUE TITLE
Premium Tier pricing is used

### ISSUE THREAD

**Issue by leecottrellPTC** [Azure/azure-docs-sdk-java#892]
This page has you build an app using the premium pricing tier. Not knowing what the tiers were, I blindly followed this page and burned through $170 in less than a week of inactivity. 

Change to the F1 pricing tier and save yourself some serious money. Shame on the author for creating a basic tutorial that utilizes the most expensive resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot JAR file app to the cloud with Maven and Azure](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by rmcmurray** [comment]
This has been fixed in #929
