### ISSUE TITLE
Jar file on app service environment, but not expanded properly 

### ISSUE THREAD

**Issue by danadrianparaschiv** [Azure/azure-docs-sdk-java#912]
Maven reports successful deploy, but when access the app URL I still get the initial index.jsp.
Checking with Kudu I see the jar outside the webapps folder. Any recommendations?

Index of /wwwroot/
webapps/		
gs-spring-boot-0.1.0.jar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 83f018e3-40db-c279-9bd0-f0de6246a1bc
* Content: [Deploy a Spring Boot JAR file app to the cloud with Maven and Azure](https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable#feedback)
* Content Source: [docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-conceptual/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @rmcmurray
* Microsoft Alias: **robmcm**

**Comment by Flanker32** [comment]
@danadrianparaschiv Thanks for your report, could you please share the configuration you used? It seems that the spring boot app is deployed to a tomcat webcontainer according to the path information.

**Comment by thisbl00d** [comment]
use  <targetPath>webapps/ROOT/${project.build.finalName}</targetPath> under builds>plugins>plugin>configuration>deployment>resources>resource

**Comment by projeffboy** [comment]
I have the exact same problem! I follow everything that this [https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-with-maven-plugin?view=azure-java-stable#feedback](tutorial) says. But when I deploy it to Azure, none of my @RequestMapping endpoints work. They go to 404. Going to the root of my site goes to index.jsp, that's all. My file structure is also like this:
```
Index of /wwwroot/
webapps/
gs-spring-boot-0.1.0.jar
```

By the way, @thisbl00d, what do you mean by your comment? In the <resource> tag, you put `webapps/ROOT/${project.build.finalName}` in it? Doesn't make sense.

**Comment by rmcmurray** [comment]
There are a host of changes in PR #929 that address all of the outstanding issues in this article, and the problem that you are seeing does not reproduce in that version of the article, which will be published shortly.
