### ISSUE TITLE
Broken link on 'Explore the Client APIs' button

### ISSUE THREAD

**Issue by haokanga** [Azure/azure-docs-sdk-java#931]
https://docs.microsoft.com/en-us/java/api/overview/azure/storage/client gives 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57d1b3c-813e-5c48-4ed7-013f11473f7f
* Version Independent ID: 8b2f0d3f-d959-d5bc-7b47-521248ac056c
* Content: [Azure Storage libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable)
* Content Source: [docs-ref-services/storage.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @douge
* Microsoft Alias: **douge**

**Comment by tamram** [comment]
@haokanga - This page has been updated. Thanks for your feedback!

#please-close
