### ISSUE TITLE
JavaDoc for Storage

### ISSUE THREAD

**Issue by TurtleBeach** [Azure/azure-docs-sdk-java#968]
Why does Microsoft persist in making it hard to find documentation??? The title of this page is Azure Storage Libraries for Java. Java programmers (certainly this one) expect(s) to see JavaDoc. Would it be so hard to put ON THIS PAGE a link DIRECTLY to the Java Doc pages for the storage lib, rather than links to whatever documentation format MS decides is the flavor of the day? Truly hard to fathom. Who owns this project??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a57d1b3c-813e-5c48-4ed7-013f11473f7f
* Version Independent ID: 8b2f0d3f-d959-d5bc-7b47-521248ac056c
* Content: [Azure Storage libraries for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/storage?view=azure-java-stable#feedback)
* Content Source: [docs-ref-services/storage.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/storage.md)
* Service: **storage**
* GitHub Login: @adrianhall
* Microsoft Alias: **adhal**

**Comment by adrianhall** [comment]
Hi @TurtleBeach - did you see the "reference docs" links - the v12 libraries reference docs are JavaDocs.  We are likely not going to be updating the older versions, and I recommend you upgrade to the latest editions of the libraries.

**Comment by brunoborges** [comment]
@adrianhall maybe a good point being made here is that we should put "Javadoc" explicitly in the ToC

**Comment by adrianhall** [comment]
That's reasonable.  I'll put in a PR to adjust.
